### ISSUE TITLE
Open FriCAS in the same shell on macOS?

### ISSUE THREAD

**Issue by ornamentist** [fricas/fricas#107]
I may be missing something, but is it possible to have the FriCAS CLI open in the same shell that issues the `...FriCAS.app/Contents/MacOS/FriCAS` command?  

At the moment it opens a new mac terminal even if I open it from iTerm2 or Kitty etc.

**Comment by oldk1331** [comment]
1. If you want to use it in terminal, I'd suggest to install FriCAS from Homebrew.

2. For the DMG package, you can run the script `...FriCAS.app/Contents/Resources/usr/local/bin/fricas`.  Note: this works directly for recent CI builds, but for 1.3.8 release, you need to set environment variable `FRICAS_PREFIX` to `...FriCAS.app/Contents/Resources/usr/local/` first.

**Comment by ornamentist** [comment]
Thanks and thank you for such an impressive application.

**Comment by ornamentist** [comment]
Is there a custom Homebrew tap(?) for FriCAS?

```
brew search fricas
==> Casks
forecast
```

I also tried the `FRICAS_PREFIX` method:

```
$ set FRICAS_PREFIX /Users/stu/Desktop/FriCAS.app/Contents/Resources/usr/local
$ /Users/stu/Desktop/FriCAS.app/Contents/Resources/usr/local/bin/fricas
The directory for FriCAS, /usr/local/lib/fricas/target/x86_64-apple-darwin19.6.0, does not exist.
Goodbye.
```

**Comment by oldk1331** [comment]
Hi, for Homebrew, what I meant is "install sbcl and compile from source."

For the environment variable, which shell are you using and why not use `export FRICAS_PREFIX=...`?  I tested, this works in zsh and bash.

(BTW, you can take a look at the shell script `.../bin/fricas`, it is pretty simple.  If you will use it frequently, you can install it into `/usr/local` or somewhere else, and tweak the script a bit to avoid setting environment every time.  OTOH, the DMG package was built for "click and launch".)

**Comment by ornamentist** [comment]
I should have noted: Fish shell. I’ll try with bash and taking a copy of the bin script.

**Comment by ornamentist** [comment]
Using `bash` works, thanks.
