### ISSUE TITLE
Build a "universal" macOS binary?

### ISSUE THREAD

**Issue by ornamentist** [fricas/fricas#108]
Would it be possible to have a universal binary build of FriCAS for recent macOS releases?  This would run natively on both x86 and Apple silicon.

I'm not sure this is possible (yet) on Github CI, I'll look into it.

**Comment by oldk1331** [comment]
The arm64 binary for macOS is planned for the future.  But GitHub Actions does not support it right now.

Even if a universal binary can not be provided, providing x86_64 and arm64 binaries separately should be easy.

**Comment by ornamentist** [comment]
Many thanks.
