### ISSUE TITLE
update config/ contents

### ISSUE THREAD

**Issue by dimpase** [fricas/fricas#11]
config/ contents are not up to date - these config.sub etc are from 2014, whereas there are updates from 2019 available.

https://www.gnu.org/software/gettext/manual/html_node/config_002eguess.html

**Comment by dimpase** [comment]
Why? This is a bug, preventing building of FriCAS on some platforms.  See https://trac.sagemath.org/ticket/23847
(it was discussed on the mailing list, too, see e.g. https://groups.google.com/g/fricas-devel/c/PTkck0eUfX4/m/AfMZmOLGAQAJ)

**Comment by dimpase** [comment]
Do you think it's normal that on some systems one has to manually replace `config.sub` with a newer version?

**Comment by hebisch** [comment]
On Wed, Jun 30, 2021 at 06:24:32AM -0700, Dima Pasechnik wrote:
> Why? This is a bug, preventing building of FriCAS on some platforms.  See https://trac.sagemath.org/ticket/23847
> (it was discussed on the mailing list, too, see e.g. https://groups.google.com/g/fricas-devel/c/PTkck0eUfX4/m/AfMZmOLGAQAJ)

Ticket says about x86_64-cygwin.  AFAICS FriCAS configure for such
target works fine.  Note that corresponding files were updated in
2018.  ATM you are re-raising problem that was solved.

-- 
                              Waldek Hebisch
