### ISSUE TITLE
)help system command no longer accepts argument (configure --with-x=no...)

### ISSUE THREAD

**Issue by gvanuxem** [fricas/fricas#112]
See title. For example:
')help trace' or ')help compile' always return the output of ')help' without argument.
At least on my machine.

**Comment by gvanuxem** [comment]
Precision, I do not build the X part: ./configure --with-x=no ..., and the *.help files are not installed with my configuration. If I install them myself, all is right. Maybe this is related.

**Comment by hemmecke** [comment]
If you have no .help files, then ")help ..." cannot work. See
https://github.com/fricas/fricas/blob/master/src/interp/i-syscmd.boot#L1057

It has nothing to do with "--with-x=no...".

**Comment by gvanuxem** [comment]
Ralf,

Yes I know but as of now some Xorg development files are necessary to
install *.help files, which is not a good thing if you only use FriCAS in a
terminal. If I install on my Debian like system xorg-dev, the different
packages listed at the end of this mail are installed and FriCAS *.help
file are installed. But without some of these packages *.help files are
generated but not installed. I just checked this night.

In fact, I use '--with-x=no ' because I do not use Xorg development files
and rarely the X server, I'm on WSL2, so I usually don't install them. I
installed these development files this night to let you know I'm right.
Something prevents installation of *.help files. The different 'awk' steps
seem good on the other hand. It could be something like htadd has to be
built before *.help files installation, I don't know. I'll take a look
deeper if necessary but I if this is a mistake in the Makefile.in file,
you're the author :)

==========================================
libbrotli-dev libdmx-dev libdmx1 libdrm-dev libfontconfig-dev
libfontconfig1-dev libfontenc-dev libfreetype-dev
  libfreetype6-dev libfs-dev libfs6 libgl-dev libglx-dev libice-dev
libpciaccess-dev libpixman-1-dev libpkgconf3
  libpng-dev libpng-tools libpthread-stubs0-dev libsm-dev libx11-dev
libxau-dev libxaw7-dev libxcb1-dev
  libxcomposite-dev libxcursor-dev libxcvt-dev libxdamage-dev libxdmcp-dev
libxext-dev libxfixes-dev libxfont-dev
  libxft-dev libxi-dev libxinerama-dev libxkbfile-dev libxmu-dev
libxmu-headers libxmuu-dev libxpm-dev
  libxrandr-dev libxrender-dev libxres-dev libxss-dev libxt-dev libxtst-dev
libxv-dev libxvmc-dev libxvmc1
  libxxf86dga-dev libxxf86vm-dev mesa-common-dev pkg-config pkgconf
pkgconf-bin uuid-dev x11proto-dev
  xorg-sgml-doctools xserver-xorg-dev xtrans-dev
Veuillez utiliser « sudo apt autoremove » pour les supprimer.
Les paquets suivants seront ENLEVÉS :
  xorg-dev


Le lun. 26 déc. 2022 à 23:12, Ralf Hemmecke ***@***.***> a
écrit :

**Comment by hemmecke** [comment]
> ...but as of now some Xorg development files are necessary to install *.help files, which is not a good thing

You seem to be right. When I wrote src/doc/Makefile.in I did not consider "terminal-use-only". However, as far as I can see from
https://github.com/fricas/fricas/blob/master/src/doc/Makefile.in#L524
there is no need for and X environment in order to generate the .help files. Give me some time for a deeper look.

**Comment by gvanuxem** [comment]
Just a precision for information, without Xorg development files the *.help
files are not generated. They are generated if the copy-to-target rule is
modified like this:
copy-to-target: stamp-bitmaps copy-helpfiles copy-gloss
                        test -d ${PREGENERATED}/target/share \
                                || ${MAKE} make-then-copy-to-target

_but_ if and only if I ran 'make' in _src/doc_ directory.




Le mar. 27 déc. 2022 à 23:07, Ralf Hemmecke ***@***.***> a
écrit :

**Comment by hemmecke** [comment]
The problem is/was that the build of helpfiles depends/depended on X. I made sure in the following commit (branch "helpfiles" that the helpfiles are built also when "--with-x=no" is active.

https://github.com/hemmecke/fricas/commit/a6810872aa8efa0b4ebd74a16cfb61e02e80d697

Please check it.

**Comment by gvanuxem** [comment]
Fine.Thanks
__
Greg

Le ven. 30 déc. 2022 à 01:41, Ralf Hemmecke ***@***.***> a
écrit :

**Comment by gvanuxem** [comment]
Hello,

In fact it remains something with .help files.
The clean or distclean Make targets let .help files in place, they are not deleted.
Same for 'stamp-ug16helpfiles".

**Comment by hemmecke** [comment]
I just checked for an "in-source-build". "make clean" in the top-level directory removes all .help files and I also see no stamp-ug16helpfiles anymore. What is the exact situation where you see these leftovers?

**Comment by gvanuxem** [comment]
I can reproduce what I'm saying with also an "in-source-build" just cloned. My configure setup is:

┌──(greg㉿ellipse)-[~/Git/fricas]
└─$ ./configure --with-x=no --with-lisp=/home/greg/.roswell/impls/x86-64/linux/ccl-bin/1.12.1/lx86cl64

Attach are the different log output with  '>log 2>&1" here. It seems src/doc ist vergessen during the clean process.
There are the output of:
 - ./configure --with-x=no --with-lisp=/home/greg/.roswell/impls/x86-64/linux/ccl-bin/1.12.1/lx86cl64
 - make -j4
 - ls -l src/doc
 - (not the output of make install even if I did it)
-  FRICAS=./target/x86_64-linux-gnu/ and ./target/x86_64-linux-gnu/bin/fricas 
 - make clean
 - make distclean
 - ls -l src/doc
[fricas.start.gz](https://github.com/fricas/fricas/files/10781583/fricas.start.gz)
[lssrcdoc.gz](https://github.com/fricas/fricas/files/10781584/lssrcdoc.gz)
[lssrcdoc2.gz](https://github.com/fricas/fricas/files/10781585/lssrcdoc2.gz)
[makeclean.gz](https://github.com/fricas/fricas/files/10781586/makeclean.gz)
[makedistclean.gz](https://github.com/fricas/fricas/files/10781587/makedistclean.gz)
[configure.git.log.gz](https://github.com/fricas/fricas/files/10781646/configure.git.log.gz)
[makej4.log.gz](https://github.com/fricas/fricas/files/10781855/makej4.log.gz)

If you want other files, please let me know.

Nevertheless I'll look later what, with different './configure && make' options, is going on here. 
 
Regards

**Comment by gvanuxem** [comment]
Yes!
Come likely from the '--with-x=no'

The diff (src/Makefile-s)
--- ../../Tmp/Makefile  2023-02-20 09:16:13.086112192 +0100
+++ src/Makefile        2023-02-20 09:19:26.866120017 +0100
@@ -137,7 +137,7 @@


 FRICAS_X11_CFLAGS =
-FRICAS_X11_LDFLAGS =  -lXpm  -lX11
+FRICAS_X11_LDFLAGS =  -lXpm  -lSM -lICE -lX11

 fricas_includes = -I$(fricas_src_srcdir)/include -I$(fricas_configdir)

@@ -189,7 +189,7 @@
 PACKAGE_URL = https://fricas.github.io


-SUBDIRS = lib lisp boot interp algebra input etc clef sman
+SUBDIRS = lib lisp boot interp algebra input etc clef sman graph hyper doc

 subdir = src/

@@ -200,7 +200,7 @@
 all-ax all-src: copy-helpfiles stamp
        @echo finished $(builddir)

-stamp: all-fricassys  all-sman all-clef
+stamp: all-fricassys  all-sman all-clef all-graph all-hyper all-doc
        -rm -f stamp
        $(STAMP) stamp

**Comment by hebisch** [comment]
AFAICS all issues discussed here are now resolved.
