### ISSUE TITLE
[Question] external programs interfacing with FriCAS

### ISSUE THREAD

**Issue by saona-raimundo** [fricas/fricas#124]
Thank you for all the effort to provide a CAS.

One of the explicit goals of FriCAS is to
make it easier for external programs to interface with FriCAS

But I can not find documentation to do so.
Where should I look for it? 

I am particularly interested in making an integration with Rust.

**Comment by hebisch** [comment]
On Wed, May 17, 2023 at 04:55:46AM -0700, Raimundo Saona wrote:
> Thank you for all the effort to provide a CAS.
> 
> One of the explicit goals of FriCAS is to
> make it easier for external programs to interface with FriCAS
> 
> But I can not find documentation to do so.
> Where should I look for it? 
> 
> I am particularly interested in making an integration with Rust.

That is question that really should go to FriCAS mailing list.
FriCAS depends on Lisp runtime and data structures and interaction
with other language involves copy or convertion of data.  ATM
programs interacting with FriCAS use textual form.  FriCAS has
special mechinizm (makers) to make it easier to parse FriCAS
output.  Also, there are choices of output format.  But that
is not normal user stuff, so best source of information is
mailing list archive.  If principle googling for FriCAS and
marker should find this, but I am affraid that you need
special tricks for Google to fing it.

There is another possibility, FriCAS can be loaded as Lisp library,
look at 'contrib/load-fricas.lisp' (there is short explantaion
inside).

-- 
                              Waldek Hebisch

**Comment by saona-raimundo** [comment]
Thank you!
In the mailing list, this was a recent question:
`run external command and capture output without temporary files`
https://groups.google.com/g/fricas-devel/c/29dm-jO9zIg/m/SBYI-EIxAQAJ

There, the question was about how to call Sage from FriCAS.
