### ISSUE TITLE
Add 'distclean-local' target in src/doc/Makefile.in

### ISSUE THREAD

**Issue by gvanuxem** [fricas/fricas#126]
Actually, issuing a ``make distclean`` does not clean the src/doc sub-directory. Only a ``make clean`` will do .
This becomes problematic when, for example, you rebuild FriCAS with another LISP implementation. This will lead to numerous warning messages when HyperDoc starts.

If we read config/setup-dep.mk we have:

```
## Cleanup.
##   Each Makefile is responsible of defining targets named
##   mostlyclean-local, clean-local, and distclean-local.
```

So since the src/doc/Makefile.in only contains:
```
clean-local: clean-book clean-html
	-rm -f ${GEN_NONVIEWPORTFILES_PHT} ${GEN_VIEWPORTFILES_PHT}
	-rm -f ${GEN_FILES_HT} *.input *.help *.text *.ps
	-rm -rf tmp
	-rm -f examples.* stamp* ht.db
	-rm -rf *.VIEW viewports test*.svg *.sfort
```
I suggest to add the missing targets or at least ``distclean-local``. Personally I just modified my src/doc/Makefile.in copy to:
```
##########################################################
mostlyclean-local:
	-rm -f ${GEN_NONVIEWPORTFILES_PHT} ${GEN_VIEWPORTFILES_PHT}
	-rm -f ${GEN_FILES_HT} *.input *.help *.text *.ps
	-rm -rf tmp
	-rm -f examples.* stamp* ht.db
	-rm -rf *.VIEW viewports test*.svg *.sfort

clean-local: clean-book clean-html mostlyclean-local

distclean-local: clean-local
```
But any comments or suggestions are welcome.

**Comment by hemmecke** [comment]
I had a short look into it. Indeed, it seems that I should change the line 
https://github.com/fricas/fricas/blob/master/src/doc/Makefile.in#LL804C20-L804C20
```
clean-local: clean-book clean-html
```
into
```
mostlyclean-local clean-local distclean-local: clean-book clean-html
```
and that would do the job.
Patch will come when I have tested it.
Greg, maybe you can already test it on your side.

**Comment by gvanuxem** [comment]
This does the job indeed. Not used to read that in one line though.

**Comment by hebisch** [comment]
Done in slightly different way.
