### ISSUE TITLE
Integration

### ISSUE THREAD

**Issue by pawn4** [fricas/fricas#128]
i want to integrate the following function:asinh(x)/x but the fricas doesnt do it.i have windows and i use the 1.3.8 version.thanks in advance!

**Comment by hebisch** [comment]
On Mon, Jun 19, 2023 at 05:32:59AM -0700, pawn4 wrote:
> i want to integrate the following function:asinh(x)/x but the fricas doesnt do it.i have windows and i use the 1.3.8 version.thanks in advance!

'asinh(x)/x' does not have elementary integral and probably it is
not integrable in terms of special function known to FriCAS.

You could try to do calculations in terms of unevaluated integral.
Or maybe expand your function into power series like:

(5) -> s := series(asinh(x)/x, x= 0)

            1  2    3  4    5   6    35   8    63   10      11
   (5)  1 - - x  + -- x  - --- x  + ---- x  - ---- x   + O(x  )
            6      40      112      1152      2816
                       Type: UnivariatePuiseuxSeries(Expression(Integer),x,0)
(6) -> integrate(s)

             1  3    3   5    5   7     35   9     63   11      12
   (6)  x - -- x  + --- x  - --- x  + ----- x  - ----- x   + O(x  )
            18      200      784      10368      30976
                       Type: UnivariatePuiseuxSeries(Expression(Integer),x,0)


-- 
                              Waldek Hebisch

**Comment by billpage** [comment]
For possible future reference note that FriCAS is able to verify the following result from Maple:

(1) -> -1/2*asinh(x)^2+asinh(x)*log(1+x+(x^2+1)^(1/2))+1/2*dilog(1-(x+(x^2+1)^(1/2))^2)+asinh(x)*log(1-x-(x^2+1)^(1/2));

                                                    Type: Expression(Integer)
(2) -> map(normalize,asinh(x)/x = D(%% 1,x))::Boolean                                                                   

   (2)  true
                                                                Type: Boolean
