### ISSUE TITLE
Command history doesn't work

### ISSUE THREAD

**Issue by yurivict** [fricas/fricas#132]
Pressing up-key doesn't bring up the previous command.

Version: 1.3.9
FreeBSD 13.2

**Comment by hemmecke** [comment]
That's not a problem of 1.3.9, is it?
```
fricas --help
```
tells me that there is a `-rl` option to use GNU readline.
You have to install rlwrap for this.
Otherwise, you can start efricas or install frimacs in Emacs
http://fricas.github.io/install.html#install-frimacs

**Comment by yurivict** [comment]
Thanks, @hemmecke .

It looks like when rlwrap is installed `-rl` isn't even needed.

**Comment by hemmecke** [comment]
Oh, how are you calling fricas then? According to
https://github.com/fricas/fricas/blob/master/src/etc/fricas#L177
I would be surprised if it really does what you say.

**Comment by yurivict** [comment]
> Oh, how are you calling fricas then?

I just call "fricas" (no emacs is used).

This is on the FreeBSD system, fricas is built from the port.

**Comment by hemmecke** [comment]
Strange. Can you give the output of 'fricas -nogo'?

**Comment by yurivict** [comment]
```
$ fricas -nogo
Would now execute the following.
FRICAS="/usr/local/lib/fricas/target/x86_64-linux-gnu"
export FRICAS
/usr/local/lib/fricas/target/amd64-portbld-freebsd13.2/bin/sman  -ws /usr/local/lib/fricas/target/amd64-portbld-freebsd13.2/bin/FRICASsys
```

**Comment by hemmecke** [comment]
Oh, I just saw
RLWRAP=${RLWRAP:=rlwrap}
https://github.com/fricas/fricas/blob/master/src/etc/fricas#L57
However, that would just work when you call 'fricas -nosman'.
I wonder what happens. But if you are happy, all is fine.
