### ISSUE TITLE
FriCAS banner ought to include Lisp version

### ISSUE THREAD

**Issue by dimpase** [fricas/fricas#140]
Currently it's impossible to see what Lisp is used:
```
$ fricas
Checking for foreign routines
FRICAS="/usr/lib64/fricas/target/x86_64-pc-linux-gnu"
spad-lib="/usr/lib64/fricas/target/x86_64-pc-linux-gnu/lib/libspad.so"
foreign routines found
openServer result 0
                       FriCAS Computer Algebra System 
                            Version: FriCAS 1.3.9
                   Timestamp: Mon 30 Oct 12:40:08 GMT 2023
-----------------------------------------------------------------------------
   Issue )copyright to view copyright notices.
   Issue )summary for a summary of useful system commands.
   Issue )quit to leave FriCAS and return to shell.
-----------------------------------------------------------------------------
 

(1) -> 
```

I think it's important to have in `Version: FriCAS 1.3.9` something like 
```
       Version: FriCAS 1.3.9; built with SuperDuper Lisp 42.666
```

**Comment by hemmecke** [comment]
> I think it's important to have in `Version: FriCAS 1.3.9` something like
> ```
>         Version: FriCAS 1.3.9; built with SuperDuper Lisp 42.666

We already have "fricas --version", but I agree that the lisp version 
would be good to see in the banner and also via ")version".

**Comment by hemmecke** [comment]
> I wonder if porting some of the command line argument list processing 
to Lisp level is a good idea...

Doesn't have every lisp a function that prints its version string at 
runtime? Just that should be used for the banner.
I implemented the commandline '--version' stuff in such a way that it 
need not touch FRICASsys or sman. For the banner one can actually use 
the underlying LISP itself to yield the version information.

**Comment by dimpase** [comment]
one can easily tell ./configure to write data into Lisp files (create foo.lsp.in with templates in it, etc). So "not known to Lisp" is easy to solve

**Comment by hebisch** [comment]
On Wed, Nov 22, 2023 at 03:42:53PM +0000, Dima Pasechnik wrote:
> Currently it's impossible to see what Lisp is used:
> 
> I think it's important to have in `Version: FriCAS 1.3.9` something like 
> ```
>        Version: FriCAS 1.3.9; built with SuperDuper Lisp 42.666
> ```

I have now commit a change that adds detected Lisp flavour and version
like:

           Version: FriCAS 2023-06-17 build with sbcl 2.2.9.debian

-- 
                              Waldek Hebisch

**Comment by dimpase** [comment]
I've also created #141 to fix build->built typo
