### ISSUE TITLE
[mailing list] ")dis op groebner" error only in SBCL

### ISSUE THREAD

**Issue by oldk1331** [fricas/fricas#152]
https://www.mail-archive.com/fricas-devel@googlegroups.com/msg15943.html

````
(1) -> )dis op groebner

There are 4 exposed functions called groebner :
   [1] List(D4) -> List(D4) from GroebnerPackage(D2,D3,D4)
            if D4 has Join(FAMR(D2,D3),ATVCWC) and D2 has GCDDOM and D3
            has OAMONS
   [2] (List(D5),String) -> List(D5) from GroebnerPackage(D3,D4,D5)
            if D5 has Join(FAMR(D3,D4),ATVCWC) and D3 has GCDDOM and D4
            has OAMONS
   [3] (List(D5),String,String) -> List(D5) from GroebnerPackage(D3,D4,
            D5)
            if D5 has Join(FAMR(D3,D4),ATVCWC) and D3 has GCDDOM and D4
            has OAMONS
   [4] PolynomialIdeal(D1,D2,D3,D4) -> PolynomialIdeal(D1,D2,D3,D4)
            from PolynomialIdeal(D1,D2,D3,D4)
            if D1 has FIELD and D2 has OAMONS and D3 has ORDSET and D4 
            has POLYCAT(D1,D2,D3)


There are 6 unexposed functions called groebner :

   >> System error:
   The value
  (|#| D4)
is not of type
  INTEGER
when binding |n|
````

With the help of fricas0 and fricas0-repo, it is easily bisected to commit 2e4faf4b (2022-01-15).

So the added check in this commit exposed the bug, and only SBCL executes the check.

Longer reply by Waldek at:
https://www.mail-archive.com/fricas-devel@googlegroups.com/msg15947.html

**Comment by gvanuxem** [comment]
Same thing with ')display operations  monomial':

(1) -> )di op monomial

There are 4 exposed functions called monomial :
   [1] (D1,List(PositiveInteger)) -> CliffordAlgebra(D3,D1,D4)
            from CliffordAlgebra(D3,D1,D4)
            if D3: PI and D1 has FIELD and D4: SQMATRIX(D3,D1)
   [2] (D,List(D4),List(NonNegativeInteger)) -> D from D
            if D has MTSCAT(D3,D4) and D3 has RING and D4 has ORDSET

   [3] (D,D1,NonNegativeInteger) -> D from D
            if D has MTSCAT(D3,D1) and D3 has RING and D1 has ORDSET

   [4] (D1,FreeMonoid(D3)) -> D from D
            if D3 has ORDSET and D has XFALG(D3,D1) and D1 has RING

There are 6 unexposed functions called monomial :

   >> System error:
   The value
  (|#| D3)
is not of type
  INTEGER
when binding |n|

Is there a temporary workaround other than reverting commit https://github.com/fricas/fricas/commit/2e4faf4b1ff681bd82fb086246fd19726ce0c729 (2022-01-15) ? I do not want to revert this commit when I build FriCAS but even a small temporary workaround would be handy.
