### ISSUE TITLE
Assumption system?

### ISSUE THREAD

**Issue by linwaytin** [fricas/fricas#156]
The default output of `integrate` contains a list of all possible parameters. For example, `integrate(1/(x^2+a), x)` gives 2 answers. Is there a way to assume `a>0` and only give one answer. 

In Maxima, there is `assume(a>0)`. I'm wondering if there is a similar function in Fricas. 

Thanks.

**Comment by hebisch** [comment]
On Mon, Feb 12, 2024 at 07:10:56AM -0800, linwaytin wrote:
> The default output of `integrate` contains a list of all possible parameters. For example, `integrate(1/(x^2+a), x)` gives 2 answers. Is there a way to assume `a>0` and only give one answer. 
> 
> In Maxima, there is `assume(a>0)`. I'm wondering if there is a similar function in Fricas.

No.  Currently FriCAS works almost exclusively in "context-free way".
However, in real situations FriCAS assumes that square is positive,
so you can do:

4) -> integrate(1/(x^2+a^2), x)

             x
        atan(-)
             a
   (4)  -------
           a
                                         Type: Union(Expression(Integer),...)


-- 
                              Waldek Hebisch

**Comment by hebisch** [comment]
On Mon, Feb 12, 2024 at 07:10:56AM -0800, linwaytin wrote:
> The default output of `integrate` contains a list of all possible parameters. For example, `integrate(1/(x^2+a), x)` gives 2 answers. Is there a way to assume `a>0` and only give one answer. 
> 
> In Maxima, there is `assume(a>0)`. I'm wondering if there is a similar function in Fricas. 
> 
> Thanks.

No.  Currently FriCAS works almost exclusively in "context-free way".
However, in real situations FriCAS assumes that square is positive,             
so you can do:

4) -> integrate(1/(x^2+a^2), x)
                                                                                
             x                                                                  
        atan(-)                                                                 
             a                                                                  
   (4)  -------                                                                 
           a                                                                    
                                         Type: Union(Expression(Integer),...)

-- 
                              Waldek Hebisch

**Comment by linwaytin** [comment]
Thanks!
