### ISSUE TITLE
WebAssembly

### ISSUE THREAD

**Issue by stefnotch** [fricas/fricas#16]
It would be quite interesting to see if it's possible to compile Fricas to WebAssembly or similar. That would make it possible to use a high quality CAS in the browser!

**Comment by hemmecke** [comment]
Do you have an idea, how to achieve it?

**Comment by stefnotch** [comment]
Judging from https://github.com/fricas/fricas/blob/master/doc/build.txt , it seems like a WebAssembly implementation of Lisp would be a first step. I'm not sure if there are any that are good enough or which ones would be worth keeping an eye on.

**Comment by hemmecke** [comment]
Indeed, FriCAS is mostly Lisp, but not everything. If you are interested in such a project, you are welcome to procede. Unfortunatly, I am totally unfamiliar with Wasm and don't know of anyt LISP->WASM compiler. Please take the lead. You will certainly get any help, but personally I somehow doubt that FriCAS on wasm is an easy project. I rather tend to provide client access to a FriCAS running on a server. 
As far as I understand, wasm runs in the browser of the client so there would be need to transmit the relevant part of a FriCAS-on-wasm from some website to the client's browser. Wouldn't that be too much?

**Comment by stefnotch** [comment]
After some more digging, it doesn't seem like there are any decent projects that let you run LISP code with WebAssembly or compile it to WebAssembly. There are LISP to Javascript translators like parenscript and JSCL, but neither of them seem to be fully developed. But I'm not very knowledgeable in this area and was hoping that someone else could chip in.

By the way, which Lisp dialect does FriCAS use?

**Comment by hemmecke** [comment]
> By the way, which Lisp dialect does FriCAS use?

We use https://groups.google.com/forum/#!forum/fricas-devel for such kind of questions. Please ask there.
