### ISSUE TITLE
Bad evaluation, for univariate polynomials, of 'x^2+2x+3' in the interpreter (should throw something)

### ISSUE THREAD

**Issue by gvanuxem** [fricas/fricas#163]
The following input in the interpreter is strangely evaluated. It's incorrect input but the interpreter should not return this. For comparaison I added the output of the same input with the multivariate polynomial domain.

```
Checking for foreign routines
FRICAS="/home/greg/.local/lib/fricas/target/x86_64-linux-gnu"
spad-lib="/home/greg/.local/lib/fricas/target/x86_64-linux-gnu/lib/libspad.so"
foreign routines found
openServer result -2
                       FriCAS Computer Algebra System
           Version: FriCAS 2023-06-17 built with sbcl 2.4.1.debian
                  Timestamp: mer. 20 mars 2024 19:03:38 CET
-----------------------------------------------------------------------------
   Issue )copyright to view copyright notices.
   Issue )summary for a summary of useful system commands.
   Issue )quit to leave FriCAS and return to shell.
-----------------------------------------------------------------------------

(1) -> VarSet: List Symbol:=["x", "y"]

   (1)  [x, y]
                                                           Type: List(Symbol)
(2) -> x:=x::UP("x",INT)

   (2)  x
                                        Type: UnivariatePolynomial(x,Integer)
(3) -> x^2+2x+3

         2
   (3)  x  + 5
                                        Type: UnivariatePolynomial(x,Integer)
(4) -> x^2+2*x+3

         2
   (4)  x  + 2 x + 3
                                        Type: UnivariatePolynomial(x,Integer)
(5) -> )cl prop x
(5) -> x:=x::MPOLY(VarSet,INT)

   (5)  x
                                  Type: MultivariatePolynomial([x,y],Integer)
(6) -> x^2+2x+3

   Cannot find a definition or applicable library operation named 2
      with argument type(s)
                    MultivariatePolynomial([x,y],Integer)

      Perhaps you should use "@" to indicate the required return type,
      or "$" to specify which version of the function you need.

(6) -> x^2+2*x+3

         2
   (6)  x  + 2 x + 3
                                  Type: MultivariatePolynomial([x,y],Integer)
(7) ->
```

**Comment by hebisch** [comment]
On Sat, Apr 06, 2024 at 08:47:46AM -0700, Grégory Vanuxem wrote:
> The following input in the interpreter is strangely evaluated.
> It's incorrect

Unfortunately, it is correct, but has strange meaning.

> input but the interpreter should not return this. For comparaison I added the output of the same input with the multivariate polynomial domain.
> 
> ```
> Checking for foreign routines
> FRICAS="/home/greg/.local/lib/fricas/target/x86_64-linux-gnu"
> spad-lib="/home/greg/.local/lib/fricas/target/x86_64-linux-gnu/lib/libspad.so"
> foreign routines found
> openServer result -2
>                        FriCAS Computer Algebra System
>            Version: FriCAS 2023-06-17 built with sbcl 2.4.1.debian
>                   Timestamp: mer. 20 mars 2024 19:03:38 CET
> -----------------------------------------------------------------------------
>    Issue )copyright to view copyright notices.
>    Issue )summary for a summary of useful system commands.
>    Issue )quit to leave FriCAS and return to shell.
> -----------------------------------------------------------------------------
> 
> (1) -> VarSet: List Symbol:=["x", "y"]
> 
>    (1)  [x, y]
>                                                            Type: List(Symbol)
> (2) -> x:=x::UP("x",INT)
> 
>    (2)  x
>                                         Type: UnivariatePolynomial(x,Integer)
> (3) -> x^2+2x+3
> 
>          2
>    (3)  x  + 5
>                                         Type: UnivariatePolynomial(x,Integer)
> (4) -> x^2+2*x+3
> 
>          2
>    (4)  x  + 2 x + 3
>                                         Type: UnivariatePolynomial(x,Integer)
> (5) -> )cl prop x
> (5) -> x:=x::MPOLY(VarSet,INT)
> 
>    (5)  x
>                                   Type: MultivariatePolynomial([x,y],Integer)
> (6) -> x^2+2x+3
> 
>    Cannot find a definition or applicable library operation named 2
>       with argument type(s)
>                     MultivariatePolynomial([x,y],Integer)
> 
>       Perhaps you should use "@" to indicate the required return type,
>       or "$" to specify which version of the function you need.
> 
> (6) -> x^2+2*x+3
> 
>          2
>    (6)  x  + 2 x + 3
>                                   Type: MultivariatePolynomial([x,y],Integer)
> (7) ->
> ```
> 

Compare
```
(1) -> p1 := 2::UP("x",INT)

   (1)  2
                                        Type: UnivariatePolynomial(x,Integer)
(2) -> p2 := x::UP("x",INT)

   (2)  x
                                        Type: UnivariatePolynomial(x,Integer)
(3) -> p1(p2)

   (3)  2
                                        Type: UnivariatePolynomial(x,Integer)
(4) -> 2p2

   (4)  2
                                        Type: UnivariatePolynomial(x,Integer)
```

(3) above is usual composition of polynomials.  Syntacticaly, '2x' and
'2(x)' are considered indentical in FriCAS, so once interpreter decided
to coerce '2' to 'UP("x",INT)' (4) is treated the same as (3).

-- 
                              Waldek Hebisch
