### ISSUE TITLE
Strange characters in documentation

### ISSUE THREAD

**Issue by pietvo** [fricas/fricas#165]
There are a few places in the PDF of the fricas book were `<` signs are not properly processed. They come out as `¡` instead, which happens in TeX when you use `<` in text mode (other than `\tt` font) instead of math mode (`$<$`).

In  `doc/htex/ug04.htex`, line 1067:
`like '\%e < \%pi' -- now FriCAS will complain about '<' being`

In `doc/htex/ZDSOLVE.htex`, line 195: `variables is {\bf t < z < y < x }.`

These come out correctly in the hyperdoc.

I don't know enough about the `htex` conventions to correct this, maybe use something like
   `{\tt \%e < \%pi}` or use `\texht{$<$}{<}` or `\spadcommand{...}`.

**Comment by hemmecke** [comment]
This pull request fixes the problem. I will commit tomorrow.
https://github.com/fricas/fricas/compare/master...hemmecke:fricas:docfix-mathexpression

**Comment by hemmecke** [comment]
fixed by 1e841325b5760a5ac1c3ad83e938669bed35039e
