### ISSUE TITLE
HyperDoc is not closed if it is only started with the system command synonym ')hd'

### ISSUE THREAD

**Issue by gvanuxem** [fricas/fricas#170]
Closing FriCAS with  a HyperDoc window started only via ')hd'  does not close it (fricas -noht).

**Comment by oldk1331** [comment]
Just like `|stopGraphics|` is implemented as `)lisp (|sockSendSignal| 2 15)`, hyperdoc window can be closed by `)lisp (|sockSendSignal| 3 15)`.

Maybe we should do this check at `quitSpad2Cmd`.

**Comment by oldk1331** [comment]
I took a deeper look.

In the HyperDoc mainEventLoop, when FRICASsys (spad server) quits, the `get_int` call will fail, indicating the socket is closed.  In this case, we should close hyperdoc, just like what "viewman" did. 

````
diff --git a/src/hyper/event.c b/src/hyper/event.c
index a0f0c058..49ef7b4e 100644
--- a/src/hyper/event.c
+++ b/src/hyper/event.c
@@ -127,10 +127,13 @@ mainEventLoop(void)
                      * $PageStuff in hypertex.boot
                      */
                 {
-                    if (100 == get_int(spad_socket)) {
+                    int cmd = get_int(spad_socket);
+                    if (100 == cmd) {
                         set_window(gParentWindow->fMainWindow);
                         make_busy_cursors();
                         get_new_window();
+                    } else if (-1 == cmd) {
+                        exitHyperDoc();
                     }
                 }
                 /*
````

**Comment by gvanuxem** [comment]
Hello,

I don't know if there are other/better ways to achieve this but that works
nicely, thanks for this!

- Greg
