### ISSUE TITLE
spoonComp.c and spoon2D.c referenced undeclared function `fricas_sleep()`

### ISSUE THREAD

**Issue by LdBeth** [fricas/fricas#173]
Adding these to lines to `fricas/src/graph/viewAlone/spoonComp.c` and `spoon2D.c` should work around the compilation problem.

```
#include "com.h"
#include "sockio-c.H1"
```

**Comment by hebisch** [comment]
On Sat, May 25, 2024 at 11:03:12AM -0700, LdBeth wrote:
> Adding these to lines to `fricas/src/graph/viewAlone/spoonComp.c` and `spoon2D.c` should work around the compilation problem.
> 
> 
> ```
> #include "com.h"
> #include "sockio-c.H1"
> ```

Thanks, done.

-- 
                              Waldek Hebisch
