### ISSUE TITLE
 toString(3.7, digits()$Float) => "4.30000000000000000000"

### ISSUE THREAD

**Issue by gvanuxem** [fricas/fricas#179]
See title.

For a discussion about this issue on the fricas-devel Google groups:

https://groups.google.com/g/fricas-devel/c/TIzdZlqFUHo

**Comment by oldk1331** [comment]
Fixed by https://github.com/fricas/fricas/commit/b53b7b8c2984c72350690e5fabce5b9f88d06b64.
