### ISSUE TITLE
Build failed on riscv64: cannot guess build type; you must specify one. 

### ISSUE THREAD

**Issue by qyl27** [fricas/fricas#182]
I am trying to package fricas for a Linux distro on riscv64 architecture.  
Using the latest release, got a build error, configure: error: cannot guess build type; you must specify one.  
It was caused by outdated `config.guess` and `config.sub` file in the latest release (1.3.11). And it should be kept up-to-date.  
Could you update it in the next release version?

**Comment by oldk1331** [comment]
Can you try to build with https://github.com/fricas/fricas/pull/181?

BTW, which distro are you packaging and which Lisp do you plan to use?

I was using opensuse Tumbleweed and built SBCL from source on riscv64.
