### ISSUE TITLE
the `gcd` defined for Euclidean domains seems incorrect for types that are not integers, such as fractions of integers

### ISSUE THREAD

**Issue by nsajko** [fricas/fricas#183]
`gcd(3/7, 6/7)` should equal `gcd(3, 6) / 7`, right? Fricas doesn't think so:

```none
(1) -> gcd(3, 6)

   (1)  3
                                                        Type: PositiveInteger
(2) -> gcd(3/7, 6/7)

   (2)  1
```

The issue seems to be that the Euclidean algorithm for *all* euclidean domains is implemented using `rem`, instead of using subtraction:

https://github.com/fricas/fricas/blob/5a7a56aab971354823c20eace6d532396dd8a176/src/algebra/catdef.spad#L492-L492

Using Euclidean division (`rem`) is a valid performance optimization for integers, but I don't think it makes sense to do it for Euclidean domains in general?

**Comment by hebisch** [comment]
On Fri, Oct 11, 2024 at 06:18:05PM -0700, Neven Sajko wrote:
> `gcd(3/7, 6/7)` should equal `gcd(3, 6) / 7`, right? Fricas doesn't think so:
> 
> ```none
> (1) -> gcd(3, 6)
> 
>    (1)  3
>                                                         Type: PositiveInteger
> (2) -> gcd(3/7, 6/7)
> 
>    (2)  1
> ```
> 
> The issue seems to be that the Euclidean algorithm for *all* euclidean domains is implemented using `rem`, instead of using subtraction:
> 
> https://github.com/fricas/fricas/blob/5a7a56aab971354823c20eace6d532396dd8a176/src/algebra/catdef.spad#L492-L492
> 
> Using Euclidean division (`rem`) is a valid performance optimization for integers, but I don't think it makes sense to do it for Euclidean domains in general?

Note that GCD is only unique modulo units.  In particular, over field
if at least one of elements in nonzero, then 1 is valid GCD and
FriCAS delivers it (see implementation of Field).

Using subtraction only works over integers, it does not work over
more general Euclidean domains.

Some people define GCD for fraction fields of unique factorization
domains, but such definition depends on choice of representation
as a fraction field so in general is problematic.

-- 
                              Waldek Hebisch

**Comment by oldk1331** [comment]
This shows that `gcd` of fractions of integers is implemented in Field:

````
(1) -> gcd$FRAC INT

   (1)  theMap(FIELD-;gcd;3S;6,655)
````

The implementation is here:
https://github.com/fricas/fricas/blob/5a7a56aab971354823c20eace6d532396dd8a176/src/algebra/catdef.spad#L600

My argument is similar to Waldek's: gcd is unique up to multiplication by units, and in Field, non-zero elements are units.

**Comment by nsajko** [comment]
Interesting. Thank you for the explanations, then.
