### ISSUE TITLE
integrate: implementation incomplete (constant residues)

### ISSUE THREAD

**Issue by s-kostyaev** [fricas/fricas#19]
This code breaks fricas:
```
 integrate(log(1+x)/x/(1+(1+x)^(1/2))^(1/2), x)
 
   >> Error detected within library code:
   integrate: implementation incomplete (constant residues)
```

**Comment by hebisch** [comment]
On Fri, Oct 23, 2020 at 12:04:29PM -0700, Sergey Kostyaev wrote:
> This code breaks fricas:
> ```
>  integrate(log(1+x)/x/(1+(1+x)^(1/2))^(1/2), x)
>  
>    >> Error detected within library code:
>    integrate: implementation incomplete (constant residues)
> ```

This is not a bug, but a feature: when FriCAS gets to
unimplemented part of Risch algorithm it gives error
instead of returning unevaluated result.

Arguably user should have choice between error and
unevaluated result, but currently this not supported...

-- 
                              Waldek Hebisch

**Comment by s-kostyaev** [comment]
I think that returning error is better than wrong result. But all documentation said that fricas has full implementation of Risch algorithm. Isn't it a big I that case?

**Comment by hebisch** [comment]
On Fri, Oct 23, 2020 at 01:16:23PM -0700, Sergey Kostyaev wrote:
> I think that returning error is better than wrong result. But all documentation said that fricas has full implementation of Risch algorithm. Isn't it a big I that case?

See:

http://fricas-wiki.math.uni.wroc.pl/RischImplementationStatus

-- 
                              Waldek Hebisch

**Comment by s-kostyaev** [comment]
Thank you. Why don't I see this link at the fricas.github.io?

**Comment by ValZapod** [comment]
Mathematica 13 now due to very nice https://github.com/stblake/algebraic_integration/commits/master included as part of Integrate can now solve it in elementary functions (WolframAlpha was not yet updated to 13 though):

Integrate[Log (1 + x)/x/(1 + (1 + x)^(1/2))^(1/2), x]
```
Log ((2 (-7 - 2 Sqrt[1 + x] + 2 (1 + x)))/(3 Sqrt[1 + Sqrt[1 + x]]) - 
   Sqrt[2] ArcTanh[Sqrt[1 + Sqrt[1 + x]]/Sqrt[2]])
```

**Comment by hebisch** [comment]
On Fri, Dec 17, 2021 at 04:03:18PM -0800, Valerii Zapodovnikov wrote:
> Mathematica 13 now due to very nice https://github.com/stblake/algebraic_integration/commits/master included as part of Integrate can now solve it in elementary functions (WolframAlpha was not yet updated to 13 though):
> 
> Integrate[Log (1 + x)/x/(1 + (1 + x)^(1/2))^(1/2), x]
> ```
> Log ((2 (-7 - 2 Sqrt[1 + x] + 2 (1 + x)))/(3 Sqrt[1 + Sqrt[1 + x]]) - 
>    Sqrt[2] ArcTanh[Sqrt[1 + Sqrt[1 + x]]/Sqrt[2]])
> ```

Hmm, this result looks wrong.  AFAICS the integral is nonelementary.
FriCAS is confused here and takes wrong branch of code, this is
part of bigger problem, but otherwise would return unevaluated
result.  Just, in case I got confused by MMA syntax, I mean

f := log(1 + x)/x/(1 + (1 + x)^(1/2))^(1/2)
integrate(f, x)

-- 
                              Waldek Hebisch

**Comment by ValZapod** [comment]
Yes, I am sorry it was me who cofused MMA syntax! Log should use []. The integral is indeed nonelementary, but still:

wolframscript.exe -code 'Integrate[Log[1 + x]/x/(1 + (1 + x)^(1/2))^(1/2), x]'
-8*ArcTanh[1/Sqrt[1 + Sqrt[1 + x]]] - (2*Log[1 + x])/Sqrt[1 + Sqrt[1 + x]] + (Log[1 + x]*Log[1 - Sqrt[2]/Sqrt[1 +
Sqrt[1 + x]]])/Sqrt[2] - (Log[1 + x]*Log[1 + Sqrt[2]/Sqrt[1 + Sqrt[1 + x]]])/Sqrt[2] - Sqrt[2]*(Log[1 + Sqrt[2]]*L
og[1 + 1/Sqrt[1 + Sqrt[1 + x]]] + Log[-((2 + Sqrt[2])*(-1 + 1/Sqrt[1 + Sqrt[1 + x]]))]*Log[1 - Sqrt[2]/Sqrt[1 + Sq
rt[1 + x]]] + 2*PolyLog[2, Sqrt[2]/Sqrt[1 + Sqrt[1 + x]]] - PolyLog[2, -((-2 + Sqrt[2])*(1 + 1/Sqrt[1 + Sqrt[1 + x
]]))] + PolyLog[2, (1 + Sqrt[2])*(-1 + Sqrt[2]/Sqrt[1 + Sqrt[1 + x]])]) + Sqrt[2]*(Log[1 + Sqrt[2]]*Log[1 - 1/Sqrt
[1 + Sqrt[1 + x]]] + Log[(2 + Sqrt[2])*(1 + 1/Sqrt[1 + Sqrt[1 + x]])]*Log[1 + Sqrt[2]/Sqrt[1 + Sqrt[1 + x]]] + 2*P
olyLog[2, -(Sqrt[2]/Sqrt[1 + Sqrt[1 + x]])] - PolyLog[2, (-2 + Sqrt[2])*(-1 + 1/Sqrt[1 + Sqrt[1 + x]])] + PolyLog[
2, -((1 + Sqrt[2])*(1 + Sqrt[2]/Sqrt[1 + Sqrt[1 + x]]))])
