### ISSUE TITLE
debian packaging

### ISSUE THREAD

**Issue by alexmyczko** [fricas/fricas#2]
maybe we can use this issue to coordinate the debian packaging?

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=570362
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=570366
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=890525 (merging)
are merged, but archived:

bts unarchive 570362
bts retitle 570362 "ITP: fricas -- an advanced computer algebra system"

need be run to let know others the one running these commands will do the packaging...

i have a building package in the 2019/ subdir at
http://phd-sid.ethz.ch/debian/fricas/
if someone can test it?

**Comment by SnarkBoojum** [comment]
Can fricas be built with ecl? In Debian we already use ecl for maxima and hence sagemath, so it would be simpler.

I tried to compile myself with --with-lisp=ecl, but the configure script errors out. I tried to compile with sbcl and the @ethz.ch Debian packaging, but there too the configure script errors out.

("we" above because I'm one of the Debian Developer working on sagemath-related packages)

**Comment by dimpase** [comment]
@SnarkBoojum  - try `./sage -i fricas` :-) 
Fricas is an Sagemath optional package, built with ECL, naturally...

**Comment by hemmecke** [comment]
I'd prefer a Debian build on top of sbcl (with GMP enabled).

**Comment by dimpase** [comment]
well, Sagemath runs fricas as a loadable library, which is only possible with ECL.

**Comment by SnarkBoojum** [comment]
I re-downloaded the tarball from github instead of from sourceforge, and it does build better!

**Comment by hemmecke** [comment]
Note. I am the maintainer of the FriCAS github mirror. However, the official development is done at sourceforge. At github there is only a mirror of the sources, if you download a tarball, you get the sources. At sourceforge there is a tarball with some prebuilt files. If you want to build all from source then you can consider github. The releases are tagged by the version number (1.3.5 being the latest).

**Comment by SnarkBoojum** [comment]
The tarball on github indeed contains cruft, and doesn't build...

I want to build from source, but I also want upstream sources, so I'll probably ask upstream to fix their tarballs.

I'm still pondering packaging fricas : I'm not convinced by the interest yet - I'm merely dipping my toes to test the waters.

**Comment by hemmecke** [comment]
I don't know where you've got the tarball from, I've never explicitly created one. That must be a github feature that creates a tarball from the sources. Why don't you just clone? "git clone https://github.com/fricas/fricas.git; git checkout 1.3.5" It doesn't take that much time. Note that currently no other FriCAS developer get's the messages that you write here. You should use the official channel: fricas-devel@googlegroups.com . I'd be happy if you keep up with your efforts to bring FriCAS into Debian. At fricas-devel you'll find probably more people to help you with any issues. Just post your error messages there.

**Comment by alexmyczko** [comment]
From https://github.com/fricas/fricas/releases ?

For debian packages you want a .tar.gz (or .tar.xz) not a git checkout.

**Comment by dimpase** [comment]
@hemmecke every time you make a github "release" it automatically generates a tarball and a zip archive from whatever it sees fit. 
These tarballs might not even be stable - if you change the repo in some ways, these tarballs might change.

As well, there is a handy feature of "editing" a release, where you can upload your own tarballs etc related to the release.

**Comment by alexmyczko** [comment]
meanwhile i've got this updated package of 1.3.5 (it builds) http://phd-sid.ethz.ch/debian/fricas/2019/
no more lintian E: (errors)

**Comment by hemmecke** [comment]
I've not created https://github.com/fricas/fricas/releases. This might come from me tagging the repository with the respective branches by the release number. All on github is source-only. Even if it says "release" on github. It just refers to the sources that mark the respective state of the sources.
The official source release fricas-1.3.5-full.tar.bz2 contains an additional directory "pregenerated". The files there are machine independent. The files in "pregenerated" will be copied to the respective place in the build tree during "make", i.e. FriCAS also builds without the "pregenerated" directory, but with "pregenerated" one saves time in generating these files. So except for the "pregenerated" directory the github-release and the fricas-1.3.5-full tarball (from SF.net) are identical.

**Comment by SnarkBoojum** [comment]
Ouch... I tried to have a look at the files and copyrights : there are days of work to document things properly!

**Comment by SnarkBoojum** [comment]
@hemmecke I had a look at your package:  most files end up in /usr/lib/x86_64-linux-gnu/fricas, and inside that repertory, many things end up in target/x86_64-linux-gnu, which is redundant.

The compiled library files do belong to /usr/lib/x86_64-linux-gnu/fricas, but more probably directly as algebra/*fasl or some such.

The help files should probably end up in  /usr/share/fricas. I don't know what those viewports are : help too ?

The src/*.spad files... I don't know ; if they're just ascii, /usr/share/fricas too probably.

The emacs files... I think there's a mechanism to install them in Debian, but I never practiced in any case, not /usr/lib !

**Comment by alexmyczko** [comment]
@SnarkBoojum patches welcome? https://salsa.debian.org/myczko-guest/fricas

**Comment by SnarkBoojum** [comment]
@alexmyczko for the d/copyright, [here]( https://salsa.debian.org/science-team/sagemath/blob/master/debian/copyright) is an example of what it is supposed to look - no package can enter Debian without a good one...

Nice to have a salsa repo - I started like this! :-)

**Comment by alexmyczko** [comment]
@SnarkBoojum I know how d/copyrights look like, and I think your example should be more like

NOT THIS:
`Copyright: Copyright (C) 2005-2016 The Sage Development Team`

BUT THIS:
Copyright: 2005-2016 The Sage Development Team

I've written many of them, and it's a nightmare for many software packages.

**Comment by nilqed** [comment]
Hi Julien

Would be great having fricas packaged, indeed.
There's a docker file showing the deps which are necessary to build from the
official tarball (sbcl, though: changing --with-sbcl to --with-ecl should do).
Maybe it's of some help?
Cheers
Kurt

https://github.com/nilqed/fricas_docker/blob/master/fricas/Dockerfile
https://hub.docker.com/r/nilqed/fricas/

**Comment by dimpase** [comment]
we do know how do build with ECL:
https://github.com/sagemath/sage/blob/develop/build/pkgs/fricas/spkg-install

I wonder whether the lines
```
# Use newer version of config.guess and config.sub (see Trac #23847)
cp "$SAGE_ROOT"/config/config.* config
```
are still relevant, perhaps fricas has had these updated. I'll check.

**Comment by SnarkBoojum** [comment]
I'm not sure I'll do the packaging myself, but I'm all for mentoring someone who'll do it.

Checking if the build deps are correct is quite trivial, and one of the last things I would check before sponsoring an upload.

Since the goal is to use fricas also through sagemath, it should be compiled with --with-lisp=ecl.

**Comment by dimpase** [comment]
see https://github.com/fricas/fricas/issues/11 - fricas should update config/ contents

**Comment by alexmyczko** [comment]
@SnarkBoojum 

I'm not sure I should waste time on packaging it, if there's someone else already working on it? Were the RFPs renamed to ITP? (I didn't check), who is working on the packaging then?

maybe someone is on irc, and that'd help communication? freenode oftc? could be #fricas no?

**Comment by SnarkBoojum** [comment]
@alexmyczko I don't know anyone working on it apart from you : I pondered it, saw the mess and decided I don't have the time to do it...

**Comment by hemmecke** [comment]
There is a #fricas room on irc.freenode.net. But it lay dormant for many years. As I said, the main communication channel of FriCAS is the mailing list fricas-devel@googlegroups.com .

**Comment by rocky** [comment]
> if someone can test it?

I tried downloading on Ubuntu Ermine. No dice.

I didn't have a problem building it from the git clone though (aside from the myriad warnings and it taking a long time to build). 

```
$ sudo dpkg -i fricas_1.3.5-1_amd64.deb 
Selecting previously unselected package fricas.
(Reading database ... 602799 files and directories currently installed.)
Preparing to unpack fricas_1.3.5-1_amd64.deb ...
Unpacking fricas (1.3.5-1) ...
Setting up fricas (1.3.5-1) ...
Processing triggers for man-db (2.8.7-3) ...
$ /usr/bin/fricas
(HyperDoc) Cannot load font -adobe-courier-medium-r-normal--18-*-*-*-m-*-iso8859-1 ; using default.
(HyperDoc) Cannot load font -adobe-courier-medium-r-normal--18-*-*-*-m-*-iso8859-1 ; using default.
(HyperDoc) Cannot load font -adobe-courier-medium-r-normal--18-*-*-*-m-*-iso8859-1 ; using default.
(HyperDoc) Cannot load font -adobe-courier-bold-r-normal--18-*-*-*-m-*-iso8859-1 ; using default.
(HyperDoc) Cannot load font -adobe-courier-bold-o-normal--18-*-*-*-m-*-iso8859-1 ; using default.
(HyperDoc) Cannot load font -adobe-courier-medium-o-normal--18-*-*-*-m-*-iso8859-1 ; using default.
(HyperDoc) Cannot load font -adobe-courier-bold-r-normal--18-*-*-*-m-*-iso8859-1 ; using default.
$
```

Yeah, I'm aware that there is some magic I need to do to remove the font warnings above, but honestly I haven't found any fonts that look significantly better and it doesn't look like Hyperdoc supports Type1 or TTF fonts. IMHO if it did, this would go a long way towards improving the experience.

**Comment by alexmyczko** [comment]
just saw the REJECT from ftp-master for an 1.3.6 upload... my 1.3.6 build log is here:

```
checking Lisp implementation... This is SBCL 2.0.9.debian, an implementation of ANSI Common Lisp.
More information about SBCL is available at <http://www.sbcl.org/>.

SBCL is free software, provided as is, with absolutely no warranty.
It is mostly in the public domain; some portions are provided under
BSD-style licenses.  See the CREDITS and COPYING files in the
distribution for more information.
fatal error encountered in SBCL pid 1456276 tid 1456276:
Unhandled SIGILL at 0x52000e9d.

Welcome to LDB, a low-level debugger for the Lisp runtime environment.
ldb> 

```

**Comment by hebisch** [comment]
On Fri, Oct 23, 2020 at 03:43:02AM -0700, Alex Myczko wrote:
> just saw the REJECT from ftp-master for an 1.3.6 upload... my 1.3.6 build log is here:
> 
> ```
> checking Lisp implementation... This is SBCL 2.0.9.debian, an implementation of ANSI Common Lisp.
> More information about SBCL is available at <http://www.sbcl.org/>.
> 
> SBCL is free software, provided as is, with absolutely no warranty.
> It is mostly in the public domain; some portions are provided under
> BSD-style licenses.  See the CREDITS and COPYING files in the
> distribution for more information.
> fatal error encountered in SBCL pid 1456276 tid 1456276:
> Unhandled SIGILL at 0x52000e9d.
> 
> Welcome to LDB, a low-level debugger for the Lisp runtime environment.
> ldb> 
> 
> ```

This looks like very broken sbcl (or something else on the build
machine is very broken).  "checking Lisp implementation" message
comes from 'configure' and it is feeding very simple Lisp code
to sbcl.

-- 
                              Waldek Hebisch

**Comment by alexmyczko** [comment]
```
# sbcl --version
SBCL 2.0.9.debian
```

**Comment by dimpase** [comment]
fricas certainly can be `./configure`'d with SBCL 2.0.9 - so on this occasion it is a problem on Debian side.

**Comment by hemmecke** [comment]
I found this message still in my mailbox.

Recently I wanted to make my HyperDoc window appear in a readable
fontsize on a 4K display. This is what I use.

FriCAS.hyperdoc.Geometry: =1500x800+0+0
FriCAS.hyperdoc.RmFont: -adobe-courier-bold-r-*-*-34-*-*-*-*-*-*-*
FriCAS.hyperdoc.RmColor: black
FriCAS.hyperdoc.ActiveFont: -adobe-courier-bold-r-*-*-34-*-*-*-*-*-*-*
FriCAS.hyperdoc.ActiveColor: blue
FriCAS.hyperdoc.FriCASFont: -adobe-courier-bold-r-*-*-34-*-*-*-*-*-*-*
FriCAS.hyperdoc.FriCASColor: #008000
FriCAS.hyperdoc.BoldFont: -adobe-courier-bold-r-*-*-34-*-*-*-*-*-*-*
FriCAS.hyperdoc.BoldColor: red
FriCAS.hyperdoc.TtFont: -adobe-courier-bold-r-*-*-34-*-*-*-*-*-*-*
FriCAS.hyperdoc.TtColor: black
FriCAS.hyperdoc.EmphasizeFont: -adobe-courier-bold-r-*-*-34-*-*-*-*-*-*-*
FriCAS.hyperdoc.EmphasizeColor: #800080
FriCAS.hyperdoc.InputBackground: #FFFF80
FriCAS.hyperdoc.InputForeground: black
FriCAS.hyperdoc.BorderColor: black
FriCAS.hyperdoc.Background: white

Ralf

**Comment by alexmyczko** [comment]
would be great to get this solved for https://release.debian.org/bullseye/freeze_policy.html

**Comment by hebisch** [comment]
On Fri, Oct 30, 2020 at 02:40:59AM -0700, Alex Myczko wrote:
> would be great to get this solved for https://release.debian.org/bullseye/freeze_policy.html

Agreed.  However, note that is really job for Debian sbcl team
(apparently stock sbcl works OK, so failure is Debian-specific).

I am not sure what Debian sbcl maintaners would do if somebody
fills bug report with info you gave, they probably would
like something more specific.  However. in this case
it should be relatively easy to narrow down the problem.
Failure comes from the following configure snippet:

AC_MSG_CHECKING([Lisp implementation])
rm -f config_cl.out
echo '(load "'"$fricas_top_srcdir"'/config.lisp")' | $fricas_lisp

In particular, the last line fails.  So one possible
test is to run:

echo '(load "./config.lisp")' | sbcl

on build machine (with 'config.lisp' coming for toplevel FriCAS
directory).  If that fails, you have clear data for
bug report.  If the above works, then there is need to
investigate what differs between the two things...

Anyway, as I wrote Debian wants that each package has Debian
maintainer and the above is kind of work that Debian maintainer
is supposed to do...

-- 
                              Waldek Hebisch

**Comment by alexmyczko** [comment]
https://packages.debian.org/search?keywords=fricas
