### ISSUE TITLE
%iint should be internal only

### ISSUE THREAD

**Issue by hemmecke** [fricas/fricas#30]
https://groups.google.com/g/fricas-devel/c/z5oRKlb8CFI

**Comment by oldk1331** [comment]
That particular bug was fixed by https://github.com/fricas/fricas/commit/240e2641928fab6f3bd2d638c5d5c437a8f68d7a

And as said in https://www.mail-archive.com/fricas-devel@googlegroups.com/msg13846.html

````
Well, I fixed one bug.  It is unrealistic to expect that single
fix will fix all possible bugs involving %iint.  As I wrote,
when there is a bug we want to see it (to be able to fix it).
````

So I would like to closing this issue for now.
