### ISSUE TITLE
Permutation groups via CL-PERMUTATION?

### ISSUE THREAD

**Issue by stylewarning** [fricas/fricas#40]
I maintain a library called [CL-PERMUTATION](https://github.com/stylewarning/cl-permutation) written in pure ANSI Common Lisp which has facilities for dealing with permutation groups. It's not state-of-the-art like GAP & co, but it does effectively work with permutations and perm groups, and is reasonably performant.

In my brief search I wasn't able to find any functionality in Axiom dealing with permutation groups, but I may not have looked hard enough.

Is this something that could be conceivably used with or integrated into FriCAS to give it perm group functionality, without gutting CL-PERMUTATION and sprinkling it inside of FriCAS?

**Comment by stylewarning** [comment]
I see I was blatantly incorrect about the nonexistence of permutation groups: they're in `permgrps.spad`! It looks like it's using the now "old" original algorithm due to Sims. Even a small upgrade like Knuth's take on Schreier-Sims would be useful, but it also looks like it's perhaps not useful to import a third-party CL-PERMUTATION project.

I won't close this issue in case a maintainer would like to comment. (But of course they are welcome to close the issue.)

**Comment by hebisch** [comment]
On Fri, Mar 05, 2021 at 04:53:37PM -0800, Robert Smith wrote:
> I see I was blatantly incorrect about the nonexistence of permutation groups: they're in `permgrps.spad`! It looks like it's using the now "old" original algorithm due to Sims. Even a small upgrade like Knuth's take on Schreier-Sims would be useful, but it also looks like it's perhaps not useful to import a third-party CL-PERMUTATION project.

I am not sure what you mean by "Knuth's take".  What FriCAS has
is usually described as "Schreier-Sims algorithm".  We lack
improvement based on Todd-Coxeter.  We also lack some related
algorithms like conjugancy based on backtracking search.

Certainly some tuning would be good, but current FriCAS
code can handle some rather large examples.  In fact,
in some cases the most expensive part is convertion between
external representation (based on lists) to internal
representation (vectors of machine sized integers).

I certainly would be interested to know if CL-PERMUTATION can
handle some examples faster than FriCAS implementation
(except for converting representation which is known
source of slowness).

-- 
                              Waldek Hebisch

**Comment by stylewarning** [comment]
@hebisch I specifically mean Knuth's improvement on Schreier-Sims in his '91 paper [here](https://arxiv.org/abs/math/9201304). I'll attempt to benchmark my code vs. FriCAS's. If I had to make a hunch, I'd say my code is probably faster, but I'll try measuring it. What do FriCAS folks usually use to benchmark functions?

**Comment by hebisch** [comment]
On Fri, Mar 05, 2021 at 11:44:13PM -0800, Robert Smith wrote:
> @hebisch I specifically mean Knuth's improvement on Schreier-Sims in his '91 paper [here](https://arxiv.org/abs/math/9201304).

Thanks, I will look this.
> I'll attempt to benchmark my code vs. FriCAS's. If I had to make a hunch, I'd say my code is probably faster, but I'll try measuring it. What do FriCAS folks usually use to benchmark functions?

After

)set messages time on

FriCAS will print how much time each command took.  For very short
running commands running them in loop will increase time and reduce
effect of overhead.  sbcl profiler for more detailed investigation.
-- 
                              Waldek Hebisch
