### ISSUE TITLE
Build error - Mac OS X, sbcl

### ISSUE THREAD

**Issue by holtzermann17** [fricas/fricas#6]
fricas_fasl_type=fasl
fricas_lisp_flavor=sbcl
fricas_lisp_version=1.4.11.68-9456dfc60

...
   Warnings: 
      [1]  RetractableTo has no value
 
****** comp fails at level 2 with expression: ******
(|Join| (|GradedModule| |t#1| |t#2|) | << | (|RetractableTo| |t#1|) | >> |
        (CATEGORY |domain| (SIGNATURE 1 ($) |constant|)
         (SIGNATURE |product| ($ $ $))))
****** level 2  ******
$x:= (RetractableTo t#1)
$m:= (Category)
$f:=
((((|t#2| #) (|t#1| #) (E # #) (R # #) ...)))
 
   >> Apparent user error:
   cannot compile (RetractableTo t#1) 

(1) -> mv: cannot stat 'category.daase': No such file or directory
mv: cannot stat 'compress.daase': No such file or directory
mv: cannot stat 'interp.daase': No such file or directory
mv: cannot stat 'operation.daase': No such file or directory
make[3]: *** [stamp-db] Error 1
make[2]: *** [all-ax] Error 2
make[1]: *** [all-algebra] Error 2
make: *** [all-src] Error 2

**Comment by oldk1331** [comment]
See https://github.com/fricas/fricas/issues/38

Use out-of-tree build instead.
