### ISSUE TITLE
multiple rules with the same LHS but with different predicates get merged nonsensically

### ISSUE THREAD

**Issue by nsajko** [fricas/fricas#63]
Initially after reading the manual section on predicates in rules, I expected that I will be able to specify Rulesets so that rules in the Ruleset can match different patterns depending on their predicates. This is obviously wrong, however, there also seem to be some bugs.

Consider this:

```
(1) -> )read testreduce.input
sum_rule_1 := rule
  sin(X)^(Y | even?(Y)) == sum(cos(n * X), n = 1..Y)
  sin(X)^(Y | odd?(Y))  == sum(sin(n * X), n = 1..Y)


                      Y                           Y
               Y     --+                   Y     --+
   (1)  {sin(X)  ==  >     cos(X n), sin(X)  ==  >     sin(X n)}
                     --+                         --+
                    n = 1                       n = 1
                           Type: Ruleset(Integer,Integer,Expression(Integer))

sum_rule_2 := rule
  sin(X)^(Y | odd?(Y))  == sum(sin(n * X), n = 1..Y)
  sin(X)^(Y | even?(Y)) == sum(cos(n * X), n = 1..Y)


                      Y                           Y
               Y     --+                   Y     --+
   (2)  {sin(X)  ==  >     sin(X n), sin(X)  ==  >     cos(X n)}
                     --+                         --+
                    n = 1                       n = 1
                           Type: Ruleset(Integer,Integer,Expression(Integer))

sum_rule_3 := rule
  sin(X)^(Y | integer?(Y) and even?(integer(Y))) == sum(cos(n * X), n = 1..Y)
  sin(X)^(Y | integer?(Y) and odd?(integer(Y)))  == sum(sin(n * X), n = 1..Y)


                      Y                           Y
               Y     --+                   Y     --+
   (3)  {sin(X)  ==  >     cos(X n), sin(X)  ==  >     sin(X n)}
                     --+                         --+
                    n = 1                       n = 1
                           Type: Ruleset(Integer,Integer,Expression(Integer))
(4) -> sum_rule_1(sin(z)^2)

   (4)  sin(2 z) + sin(z)
                                                    Type: Expression(Integer)
(5) -> sum_rule_1(sin(z)^3)

              3
   (5)  sin(z)
                                                    Type: Expression(Integer)
(6) -> sum_rule_2(sin(z)^2)

   (6)  cos(2 z) + cos(z)
                                                    Type: Expression(Integer)
(7) -> sum_rule_2(sin(z)^3)

              3
   (7)  sin(z)
                                                    Type: Expression(Integer)
(8) -> sum_rule_3(sin(z)^2)

   (8)  sin(2 z) + sin(z)
                                                    Type: Expression(Integer)
(9) -> sum_rule_3(sin(z)^3)

              3
   (9)  sin(z)
                                                    Type: Expression(Integer)
```

Each of the three Rulesets has two rules whose left-hand sides are the same except for the predicates. It seems that what happens in each of the three cases is that Fricas merges the two rules in such a way that the predicate of the first rule and the right-hand side of the second rule are kept. This is unintuitive to such a degree that it seems impossible for someone to expect that behavior, so it should probably be considered a bug.

But there's more inconsistency:

```
(1) -> )read rules_predicates.input
my_rule := rule
  sin(X)^(Y | integer?(Y) and ((integer(Y) rem 3) = 0)@Boolean) == exp_mod_3_is_0
  sin(X)^(Y | integer?(Y) and ((integer(Y) rem 3) = 1)@Boolean) == exp_mod_3_is_1
  sin(X)^(Y | integer?(Y) and ((integer(Y) rem 3) = 2)@Boolean) == exp_mod_3_is_2


              Y
   (1)  sin(X)  == exp_mod_3_is_2
                       Type: RewriteRule(Integer,Integer,Expression(Integer))
(2) -> my_rule(sin(z)^2)

   (2)  exp_mod_3_is_2
                                                    Type: Expression(Integer)
(3) -> my_rule(sin(z)^3)

   (3)  exp_mod_3_is_2
                                                    Type: Expression(Integer)
(4) -> my_rule(sin(z)^4)

   (4)  exp_mod_3_is_2
                                                    Type: Expression(Integer)
```

In this case only the last RHS counts again, but the predicates are altogether eliminated.

There seem to be many possible approaches to fixing this:
1. Add some clarifications to the manual.
2. Disallow multiple rules with the same LHS in a Ruleset. This makes Rulesets less powerful than expected, but at least there will be no unexpected behavior.
3. Make multiple rules with the same LHS but different predicates behave as expected. So `my_rule(sin(z)^3)` would equal `exp_mod_3_is_0` and `my_rule(sin(z)^4)` would equal `exp_mod_3_is_1`.

BTW, I guess that a partial workaround for when rules with different predicates but same LHS are required is to put them in different Rulesets. But this would get messy fast and I think that it's less powerful altogether.

**Comment by nsajko** [comment]
Related issue:

This code seems to work fine:

```
trigreduce_even_powers := rule
  cos(X)^(Y | even?(Y)) == binomial(Y, Y/2) / 2^Y + 2^(1 - Y) * sum(binomial(Y, k) * cos((Y - 2*k) * X), k = 0..(Y/2 - 1))
  sin(X)^(Y | even?(Y)) == binomial(Y, Y/2) / 2^Y +
                           2^(1 - Y) * sum(binomial(Y, k) * cos((Y - 2*k) * X) * (-1)^(Y/2 - k), k = 0..(Y/2 - 1))
  cos(X) * cos(Y)       == (cos(X - Y) + cos(X + Y)) / 2
  sin(X) * sin(Y)       == (cos(X - Y) - cos(X + Y)) / 2
  cos(Y) * sin(X)       == (sin(X + Y) + sin(X - Y)) / 2
```

But if I add another Ruleset definition above that definition, `trigreduce_even_powers` breaks!

Like this:

```
trigreduce_odd_powers := rule
  cos(X)^(Y | odd?(Y))  == 2^(1 - Y) * sum(binomial(Y, k) * cos((Y - 2*k) * X), k = 0..((Y - 1)/2))
  sin(X)^(Y | odd?(Y))  == 2^(1 - Y) * sum(binomial(Y, k) * sin((Y - 2*k) * X) * (-1)^((Y - 1)/2 - k), k = 0..((Y - 1)/2))
  cos(X) * cos(Y)       == (cos(X - Y) + cos(X + Y)) / 2
  sin(X) * sin(Y)       == (cos(X - Y) - cos(X + Y)) / 2
  cos(Y) * sin(X)       == (sin(X + Y) + sin(X - Y)) / 2

trigreduce_even_powers := rule
  cos(X)^(Y | even?(Y)) == binomial(Y, Y/2) / 2^Y + 2^(1 - Y) * sum(binomial(Y, k) * cos((Y - 2*k) * X), k = 0..(Y/2 - 1))
  sin(X)^(Y | even?(Y)) == binomial(Y, Y/2) / 2^Y +
                           2^(1 - Y) * sum(binomial(Y, k) * cos((Y - 2*k) * X) * (-1)^(Y/2 - k), k = 0..(Y/2 - 1))
  cos(X) * cos(Y)       == (cos(X - Y) + cos(X + Y)) / 2
  sin(X) * sin(Y)       == (cos(X - Y) - cos(X + Y)) / 2
  cos(Y) * sin(X)       == (sin(X + Y) + sin(X - Y)) / 2
```

Now trigreduce_even_powers behaves as if it had the predicates from trigreduce_odd_powers, even though they're not even in the same Ruleset!

**Comment by hebisch** [comment]
On Fri, Aug 06, 2021 at 04:08:36AM -0700, Neven Sajko wrote:
> Initially after reading the manual section on predicates in rules, I expected that I will be able to specify Rulesets so that rules in the Ruleset can match different patterns depending on their predicates. This is obviously wrong, however, there also seem to be some bugs.
> 
> Consider this:
> 
> ```
> (1) -> )read testreduce.input
> sum_rule_1 := rule
>   sin(X)^(Y | even?(Y)) == sum(cos(n * X), n = 1..Y)
>   sin(X)^(Y | odd?(Y))  == sum(sin(n * X), n = 1..Y)
> 
> 
>                       Y                           Y
>                Y     --+                   Y     --+
>    (1)  {sin(X)  ==  >     cos(X n), sin(X)  ==  >     sin(X n)}
>                      --+                         --+
>                     n = 1                       n = 1
>                            Type: Ruleset(Integer,Integer,Expression(Integer))
<snip> 
> 
> Each of the three Rulesets has two rules whose left-hand sides are the same except for the predicates. It seems that what happens in each of the three cases is that Fricas merges the two rules in such a way that the predicate of the first rule and the right-hand side of the second rule are kept. This is unintuitive to such a degree that it seems impossible for someone to expect that behavior, so it should probably be considered a bug.

This is a bug.  As a workaround you may use different variables
(variable name should not matter for working of rule).  FriCAS
used to contain code that made sure that Y-s in different rules
were considerd different variables, despite fact that in other
places they would be the same variable.  This code was (wrongly)
deleted during modification, it will be restored soon.

As an extra info: due to implementation artifacts in FriCAS
single variable has only one list of predicates.  So to support
code like yours FriCAS needs to fake new variables...

-- 
                              Waldek Hebisch

**Comment by hebisch** [comment]
Fixed by commit on 8 Aug 2021
