### ISSUE TITLE
Solution of polynomial equations in complex numbers in exponential notation?

### ISSUE THREAD

**Issue by portnov** [fricas/fricas#75]
Hello.
I'm trying to use `solve` or `radicalSolve` to obtain all solutions of polynomial equations:
```
(1) -> solve(x^5 + 1 = 0, x)

                 4    3    2
   (1)  [x= - 1,x  - x  + x  - x + 1= 0]
                          Type: List(Equation(Fraction(Polynomial(Integer))))
```
As far as I understand, what it says is that the only integer root is -1. Okay.
```
(2) -> radicalSolve(x^5 + 1 = 0, x)

   (2)
   [
     x =
           -
                2
             *
                ROOT
                                 ┌───────────────────┐2
                                 │     ┌─┐      ┌───┐
                                 │- 25\│3  + 45\│- 5
                           - 36  │───────────────────
                                3│          ┌─┐
                                \│       54\│3
                         + 
                                 ┌───────────────────┐
                                 │     ┌─┐      ┌───┐
                                 │- 25\│3  + 45\│- 5
                           - 30  │─────────────────── - 40
                                3│          ┌─┐
                                \│       54\│3
...
```
Oh, what is that? :) As far as I understand, this is how five roots of -1 are expressed in radicals in integer numbers. In hope of finding simpler answers, I also tried
```
(3) -> radicalSolve((x^5 + 1 = 0) :: Equation Polynomial Complex Fraction Integer, x)

   (3)
   [
     x =
           -
                2
             *
                ROOT
                                   ┌─────────────────┐2      ┌─────────────────┐
                                   │     ┌─┐      ┌─┐        │     ┌─┐      ┌─┐
                                   │45%i\│5  - 25\│3         │45%i\│5  - 25\│3
                             - 36  │─────────────────  - 30  │─────────────────
                                  3│         ┌─┐            3│         ┌─┐
                                  \│      54\│3             \│      54\│3
                           + 
                             - 40
                      *
                        ┌─────────────────────────────────────────────────────┐
                        │    ┌─────────────────┐2      ┌─────────────────┐
                        │    │     ┌─┐      ┌─┐        │     ┌─┐      ┌─┐
                        │    │45%i\│5  - 25\│3         │45%i\│5  - 25\│3
                        │36  │─────────────────  - 15  │───────────────── + 40
                        │   3│         ┌─┐            3│         ┌─┐
                        │   \│      54\│3             \│      54\│3
                        │─────────────────────────────────────────────────────
                        │                    ┌─────────────────┐
                        │                    │     ┌─┐      ┌─┐
                        │                    │45%i\│5  - 25\│3
                        │                36  │─────────────────
                        │                   3│         ┌─┐
                       \│                   \│      54\│3
                     + 
...
```
Now it uses `%i`, which is a bit nicer than `sqrt(-1)`.

What I was hoping for was (as in Maxima):
```
(%i1) solve(x^5+1=0, x);
               2 %i %pi          4 %i %pi            4 %i %pi
               --------          --------          - --------
                  5                 5                   5
(%o1) [x = - %e        , x = - %e        , x = - %e          , 
                                                             2 %i %pi
                                                           - --------
                                                                5
                                                   x = - %e          , x = - 1]
```

So the question is: is there a special way of involving `solve` / `radicalSolve` to obtain solutions in such simple form? Or maybe there is a separate function for that?

**Comment by hebisch** [comment]
On Thu, Dec 30, 2021 at 12:50:15AM -0800, Ilya V. Portnov wrote:
> Hello.
> I'm trying to use `solve` or `radicalSolve` to obtain all solutions of polynomial equations:
> ```
> (1) -> solve(x^5 + 1 = 0, x)
> 
>                  4    3    2
>    (1)  [x= - 1,x  - x  + x  - x + 1= 0]
>                           Type: List(Equation(Fraction(Polynomial(Integer))))
> ```
> As far as I understand, what it says is that the only integer root is -1. Okay.

More than that: it say that other roots are solution of irreducible
equation of degree 4.  This equation allows deciding if rational
expression of single root is zero, which is basically all that
is needed to effectively perform computations with root.

> ```
> (2) -> radicalSolve(x^5 + 1 = 0, x)
> 
>    (2)
>    [
>      x =
>            -
>                 2
>              *
>                 ROOT
>                                  ???????????????????????????????????????????????????????????????2
>                                  ???     ?????????      ???????????????
>                                  ???- 25\???3  + 45\???- 5
>                            - 36  ????????????????????????????????????????????????????????????
>                                 3???          ?????????
>                                 \???       54\???3
>                          + 
>                                  ???????????????????????????????????????????????????????????????
>                                  ???     ?????????      ???????????????
>                                  ???- 25\???3  + 45\???- 5
>                            - 30  ???????????????????????????????????????????????????????????? - 40
>                                 3???          ?????????
>                                 \???       54\???3
> ...
> ```
> Oh, what is that? :) As far as I understand, this is how five roots of -1 are expressed in radicals in integer numbers. In hope of finding simpler answers, I also tried
> ```
> (3) -> radicalSolve((x^5 + 1 = 0) :: Equation Polynomial Complex Fraction Integer, x)
> 
>    (3)
>    [
>      x =
>            -
>                 2
>              *
>                 ROOT
>                                    ?????????????????????????????????????????????????????????2      ?????????????????????????????????????????????????????????
>                                    ???     ?????????      ?????????        ???     ?????????      ?????????
>                                    ???45%i\???5  - 25\???3         ???45%i\???5  - 25\???3
>                              - 36  ??????????????????????????????????????????????????????  - 30  ??????????????????????????????????????????????????????
>                                   3???         ?????????            3???         ?????????
>                                   \???      54\???3             \???      54\???3
>                            + 
>                              - 40
>                       *
>                         ?????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????
>                         ???    ?????????????????????????????????????????????????????????2      ?????????????????????????????????????????????????????????
>                         ???    ???     ?????????      ?????????        ???     ?????????      ?????????
>                         ???    ???45%i\???5  - 25\???3         ???45%i\???5  - 25\???3
>                         ???36  ??????????????????????????????????????????????????????  - 15  ?????????????????????????????????????????????????????? + 40
>                         ???   3???         ?????????            3???         ?????????
>                         ???   \???      54\???3             \???      54\???3
>                         ??????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????
>                         ???                    ?????????????????????????????????????????????????????????
>                         ???                    ???     ?????????      ?????????
>                         ???                    ???45%i\???5  - 25\???3
>                         ???                36  ??????????????????????????????????????????????????????
>                         ???                   3???         ?????????
>                        \???                   \???      54\???3
>                      + 
> ...
> ```
> Now it uses `%i`, which is a bit nicer than `sqrt(-1)`.
> 
> What I was hoping for was (as in Maxima):
> ```
> (%i1) solve(x^5+1=0, x);
>                2 %i %pi          4 %i %pi            4 %i %pi
>                --------          --------          - --------
>                   5                 5                   5
> (%o1) [x = - %e        , x = - %e        , x = - %e          , 
>                                                              2 %i %pi
>                                                            - --------
>                                                                 5
>                                                    x = - %e          , x = - 1]
> ```
> 
> So the question is: is there a special way of involving `solve` / `radicalSolve` to obtain solutions in such simple form? Or maybe there is a separate function for that?

I am not sure what you really want.  'solve' produces form that is
useful in further computations (it has several uses in other parts
of FriCAS).  'radicalSolve' is really half-done, it knows formulas
but applies them blindly missing possible simplifications.
Concerning exponential form, there are some problems with it:
- exp is transcendental function and normally possible simplifications
  are relatively easy to handle.  But roots of 1 are algebraic
  with their own simplifications.
- exp form is relatively simple in this case, but in other cases it
  may quickly get quite complicated.
- in FriCAS there is question of types.  radicalSolve returns
  expressions, so you can put exponential there.  But in
  Expression(Integer) all we have is 'sqrt(-1)' (there is no
  '%i' there).

To ilustrate last point:

radicalSolve(x^5 + 2) 

   (12)
        5+---+      5+---+ +---+    2 %pi    5+---+    2 %pi
   [x = \|- 2 , x = \|- 2 \|- 1 sin(-----) + \|- 2 cos(-----),
                                      5                  5
        5+---+ +---+    4 %pi    5+---+    4 %pi
    x = \|- 2 \|- 1 sin(-----) + \|- 2 cos(-----),
                          5                  5
        5+---+ +---+    6 %pi    5+---+    6 %pi
    x = \|- 2 \|- 1 sin(-----) + \|- 2 cos(-----),
                          5                  5
        5+---+ +---+    8 %pi    5+---+    8 %pi
    x = \|- 2 \|- 1 sin(-----) + \|- 2 cos(-----)]
                          5                  5

In this case equation is irreducible, and 'radicalSolve' sees that
there is root of binomial there.  But to keep result in 'Expression(Integer)'
'radicalSolve' uses 'sqrt(-1)' and trigonometric functions...

-- 
                              Waldek Hebisch

**Comment by hebisch** [comment]
On Thu, Dec 30, 2021 at 12:50:15AM -0800, Ilya V. Portnov wrote:
> Hello.
> I'm trying to use `solve` or `radicalSolve` to obtain all solutions of polynomial equations:
> ```
> (2) -> radicalSolve(x^5 + 1 = 0, x)
> 
>    (2)
>    [
>      x =
>            -
>                 2
>              *
>                 ROOT
<snip>
> Oh, what is that? :) As far as I understand, this is how five roots of -1 are expressed in radicals in integer numbers.
<snip>
> 
> What I was hoping for was (as in Maxima):
> ```
> (%i1) solve(x^5+1=0, x);
>                2 %i %pi          4 %i %pi            4 %i %pi
>                --------          --------          - --------
>                   5                 5                   5
> (%o1) [x = - %e        , x = - %e        , x = - %e          , 
>                                                              2 %i %pi
>                                                            - --------
>                                                                 5
>                                                    x = - %e          , x = - 1]
> ```
> 
> So the question is: is there a special way of involving `solve` / `radicalSolve` to obtain solutions in such simple form? Or maybe there is a separate function for that?

As I have written, '%i' requires complex domain.  However, I have
added now code to recognize cycotomic polynomials and express
solutions in trigonometic form.  So in trunk we have:

radicalSolve(x^5+1) 

   (2)
                    +---+    2 %pi        2 %pi
   [x = - 1, x = - \|- 1 sin(-----) - cos(-----),
                               5            5
           +---+    4 %pi        4 %pi          +---+    6 %pi        6 %pi
    x = - \|- 1 sin(-----) - cos(-----), x = - \|- 1 sin(-----) - cos(-----),
                      5            5                       5            5
           +---+    8 %pi        8 %pi
    x = - \|- 1 sin(-----) - cos(-----)]
                      5            5


-- 
                              Waldek Hebisch

**Comment by portnov** [comment]
Wow! Thanks!

And Happy New Year, by the way :)

**Comment by portnov** [comment]
I think this can be resolved now.
