### ISSUE TITLE
Regression in commit 2e4faf4b1ff681bd82fb086246fd19726ce0c729

### ISSUE THREAD

**Issue by hemmecke** [fricas/fricas#81]
The program
```
)abbrev pkg FOO Foo
Foo(): Exports == Implementation where
  F ==> Fraction Integer
  Exports ==> with extractNext!: List F -> F
  Implementation ==> add
    extractNext!(m: List F): F ==
        p: List F := empty()
        g := -1 -- dummy value
        if not empty? p then g: Integer := 42
        2/3
```
behaves differently in commit d6fc24f465e301a7e7ca147fde055be6a4a5d7c5 from the newer commit 2e4faf4b1ff681bd82fb086246fd19726ce0c729 .

It's not clear whether this is an improvement or a bug.
replacing the "dummy value" line by
```g: Integer := -1```
let's everything work fine. Without type declaration the compiler obviously thinks that the type of g is Fraction(Integer) and then get's confused when g is declared to be Integer later.
Interestingly, p is empty in this example.

```
(1) -> extractNext!([1,2/5,-3/7])$Foo()
 
   >> System error:
   The value
  (-1 . 1)
is not of type
  INTEGER
```

**Comment by hebisch** [comment]
On Fri, Apr 08, 2022 at 07:19:56AM -0700, Ralf Hemmecke wrote:
> The program
> ```
> )abbrev pkg FOO Foo
> Foo(): Exports == Implementation where
>   F ==> Fraction Integer
>   Exports ==> with extractNext!: List F -> F
>   Implementation ==> add
>     extractNext!(m: List F): F ==
>         p: List F := empty()
>         g := -1 -- dummy value
>         if not empty? p then g: Integer := 42
>         2/3
> ```
> behaves differently in commit d6fc24f465e301a7e7ca147fde055be6a4a5d7c5 from the newer commit 2e4faf4b1ff681bd82fb086246fd19726ce0c729 .
> 
> It's not clear whether this is an improvement or a bug.
> replacing the "dummy value" line by
> ```g: Integer := -1```
> let's everything work fine. Without type declaration the compiler obviously thinks that the type of g is Fraction(Integer) and then get's confused when g is declared to be Integer later.
> Interestingly, p is empty in this example.
> 
> ```
> (1) -> extractNext!([1,2/5,-3/7])$Foo()
>  
>    >> System error:
>    The value
>   (-1 . 1)
> is not of type
>   INTEGER
> ```

'extractNext!' is wrong: declaration should come before use.
There is compiler bug: compiler should detect such errors.
AFAICS the only difference for this example is that due
to type declaration at Lisp level Lisp runtime checking catches
the error.

Another question is if '-1' above should be of type
Fraction(Integer).  Probably more natural would be
to treat it as Integer, however ATM there is no change
here, both before and after compiler treated it as
Fraction(Integer).

-- 
                              Waldek Hebisch
