### ISSUE TITLE
Keyword not supported, textspadexpr, in ug15.ht

### ISSUE THREAD

**Issue by gvanuxem** [fricas/fricas#82]
The output :

(1) -> (HyperDoc) Keyword not currently supported: textspadexpr
(HyperDoc) While parsing releaseNotesPage on line 710
        in the file /usr/local/lib/fricas/target/x86_64-linux-gnu/share/hypertex/pages/ug15.ht

**Comment by hemmecke** [comment]
Thank you. It is fixed with commit 1375d055842cb6bd8a9bfefe35718f53c4fbfc11 (hide \textspadsyntax, \textspadexpr, \textspadtype from HyperDoc).
