### ISSUE TITLE
Polynomial ring QQ[x]  not recognized as euclidean domain

### ISSUE THREAD

**Issue by fchapoton** [fricas/fricas#9]
(bear with me, I am not an expert in Fricas at all)

I am surprised by the following
```
fricas: Polynomial(Fraction(Integer)) has EUCDOM
false
```
Is there a way to let Fricas know that univariate polynomials over QQ form an euclidean domain ?

Motivation: I would like to apply smith() to matrices with such coefficients. This currently fails:
```
fricas: x:=x::Polynomial(Fraction(Integer))
x
fricas: m:=matrix([[4,3],[2,x]])
   +4  3+
   |    |
   +2  x+
fricas: smith(m)
There are 1 exposed and 1 unexposed library operations named smith 
      having 1 argument(s) but none was determined to be applicable. Use 
      HyperDoc Browse, or issue
                               )display op smith
      to learn more about the available operations. Perhaps 
      package-calling the operation or using coercions on the arguments 
      will allow you to apply the operation.

 
   Cannot find a definition or applicable library operation named smith 
      with argument type(s) 
                     Matrix(Polynomial(Fraction(Integer)))
      
      Perhaps you should use "@" to indicate the required return type, or 
      "$" to specify which version of the function you need.
```

**Comment by mantepse** [comment]
Salut Frederic !

(you will have much more luck asking on fricas-devel...)

As you probably have already discovered, the following works:
    (1) -> x := monomial(1,1)$UP('x, FRAC INT)
    
       (1)  x
                                  Type: UnivariatePolynomial(x,Fraction(Integer))
    (2) -> m := matrix([[x, 2],[3,4]])
    
            +x  2+
       (2)  |    |
            +3  4+
                          Type: Matrix(UnivariatePolynomial(x,Fraction(Integer)))
    (3) -> smith m
    
            +1    0  +
            |        |
       (3)  |       3|
            |0  x - -|
            +       2+
                          Type: Matrix(UnivariatePolynomial(x,Fraction(Integer)))
